### ISSUE TITLE
npm test fails at 2_deploy_contracts.js

### ISSUE THREAD

**Issue by gsampathkumar** [darcius/rocketpool#11]
Ubuntu 17.10, npm 3.5.2 node 6.11.4

Errors seen during npm test:
Compiling ./contracts/lib/SafeMath.sol...
/home/gautam/code/others/rocketpool/migrations/2_deploy_contracts.js:26
module.exports = async (deployer, network) => {
                       ^

SyntaxError: Unexpected token (
    at Object.createScript (vm.js:56:10)
    at /home/gautam/code/others/rocketpool/node_modules/truffle/build/cli.bundled.js:203298:23
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
npm ERR! Test failed.  See above for more details.

Please let me know if you need additional info and how I can help.

**Comment by darcius** [comment]
Hey @gsampathkumar! Looks like you're node version isn't 8 or greater. Try upgrading and see how it goes. See this issue #10 - Let me know if that fixes it.

**Comment by gsampathkumar** [comment]
Thanks. That was the issue. Fixed now!. Sorry, missed looking at the closed issues. Cheers and keep up the good work guys!

**Comment by darcius** [comment]
Glad you got it sorted and thanks for the good wishes, much appreciated!
