### ISSUE TITLE
Missing a license

### ISSUE THREAD

**Issue by jkcailteux** [darcius/rocketpool#9]
Hey @darcius, I would like to use this repo in a potentially profitable way, could you provide a license so I'm sure not to steal your work/illegally use your work?

Would recommend the MIT license if you don't have any strong opinions.

**Comment by darcius** [comment]
Ah good spot mate, I'll get that sorted out soon and update the ticket when I've added the license.

**Comment by gsampathkumar** [comment]
Second that. Would be great to understand Licensing.

**Comment by darcius** [comment]
Hey Guys, sorry for delay in getting around to this, got pulled over to San Fran for a while. I'm a big fan of open source, so I've added the GNU General Public License v3.0 to the repo. Hope that helps.
